services:
    example:
      build:
        dockerfile: Dockerfile
      volumes:
        - '.:/example'
        - '/example/node_modules'
      container_name: example.dev
      ports:
        - "5000:5000"
      depends_on:
        postgres:
          condition: service_healthy

    postgres:
      image: postgres:latest
      container_name: example.postgres
      restart: always
      environment:
        POSTGRES_USER: eduard
        POSTGRES_PASSWORD: test1234
        POSTGRES_DB: test
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U eduard -d test"]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  pgdata:
    driver: local