services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: eduard
        POSTGRES_PASSWORD: test1234
        POSTGRES_DB: test
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: